package pdl;

/**
 * Alarm name has to be the same as a key in pdl.res.TextBundle
 */
public enum Alarm
{
	ALARM_DRONE_NOT_FOUND,
	ALARM_SEND_ERROR,
	ALARM_RECEIVE_ERROR,
	ALARM_LOW_BATTERY,
	ALARM_LOW_BATTERY_CRITICAL,
	ALARM_LOW_RADIO_SIGNAL,
	ALARM_ENABLE_VELOCITY_Z_PID,
	ALARM_DISABLE_VELOCITY_Z_PID,
	ALARM_ENABLE_ALT_PID,
	ALARM_GPS_NOT_FIXED,
	ALARM_VERT_VELO_NOT_NULL,
	ALARM_DANGER_LEVEL,
	ALARM_IMU_NOT_READY,
	ALARM_MAGNETO_NOT_READY,
	ALARM_CONNECTING,
	ALARM_UNSUPPORTED_FIRMWARE
}
